---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linstor-api-ca-test
spec:
  commonName: linstor-api-ca-test
  secretName: linstor-api-ca-test
  duration: 87600h # 10 years
  isCA: true
  usages:
    - signing
    - key encipherment
    - cert sign
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linstor-internal-ca-test
spec:
  commonName: linstor-internal-ca-test
  secretName: linstor-internal-ca-test
  duration: 87600h # 10 years
  isCA: true
  usages:
    - signing
    - key encipherment
    - cert sign
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linstor-gui-tls-test
spec:
  commonName: linstor-gui-tls-test
  dnsNames:
    - linstor-gui-tls-test
  issuerRef:
    kind: Issuer
    name: linstor-api-ca-test
  secretName: linstor-gui-tls-test
  usages:
    - client auth