---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/issuer_v1.json
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linstor-api-ca-test
spec:
  ca:
    secretName: linstor-api-ca-test
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linstor-internal-ca-test
spec:
  ca:
    secretName: linstor-internal-ca-test