---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: suwayomi
spec:
  chartRef:
    kind: OCIRepository
    name: suwayomi
  interval: 15m
  values:
    controllers:
      suwayomi:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/suwayomi/tachidesk
              tag: "v2.1.1997"
            env:
              BIND_PORT: &port 4567
            resources:
              requests:
                memory: 250Mi
                cpu: 500m
              limits:
                memory: 1500Mi
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["{{ .Release.Name }}.musai.ovh"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        type: persistentVolumeClaim
        suffix: config
        size: 2Gi
        storageClass: linbit-replicated
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /home/suwayomi/.local/share/Tachidesk
   #   downloads:
   #     existingClaim: nfs-pictures
   #     advancedMounts:
   #       suwayomi:
   #         app:
   #           - path: /home/suwayomi/.local/share/Tachidesk/downloads/mangas
   #             subPath: mangas
   #           - path: /home/suwayomi/.local/share/Tachidesk/downloads/thumbnails
   #             subPath: thumbnails
   #   tmpfs:
   #     type: emptyDir
   #     advancedMounts:
   #       suwayomi:
   #         app:
   #           - path: /home/suwayomi/.local/share/Tachidesk/bin
   #             subPath: bin
   #           - path: /home/suwayomi/.local/share/Tachidesk/logs
   #             subPath: logs
   #           - path: /tmp
   #             subPath: tmp
