---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: suwayomi
spec:
  chartRef:
    kind: OCIRepository
    name: suwayomi
  interval: 15m
  values:
    controllers:
      suwayomi:
        containers:
          app:
            image:
              repository: ghcr.io/suwayomi/tachidesk
              tag: v2.1.1999@sha256:831f4ded150c83dfb63e6a8b9ff0c71fdb7d1eeb6e931a5e2bd16f62cc5ded1b

