---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app suwayomi
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: suwayomi
  values:
    controllers:
      suwayomi:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/suwayomi/tachidesk
              tag: v2.1.1997
            env:
              TZ: Europe/London
              BIND_PORT: &port 4567
              WEB_UI_CHANNEL: "preview"
              AUTO_DOWNLOAD_CHAPTERS: true
              UPDATE_EXCLUDE_UNREAD: "false"
              UPDATE_EXCLUDE_STARTED: "false"
              UPDATE_EXCLUDE_COMPLETED: "false"
              DOWNLOAD_AS_CBZ: "true"
              EXTENSION_REPOS: '["https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json"]'
              FLARESOLVERR_ENABLED: false
              FLARESOLVERR_URL: http://flaresolverr.downloads
          #  envFrom:
          #    - secretRef:
          #        name: suwayomi-config
            resources:
              requests:
                memory: 250Mi
                cpu: 500m
              limits:
                memory: 1500Mi
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.musai.ovh"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
    persistence:
      config:
        type: persistentVolumeClaim
        suffix: config
        size: 2Gi
        storageClass: linbit-replicated
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /home/suwayomi/.local/share/Tachidesk
   #   downloads:
   #     existingClaim: nfs-pictures
   #     advancedMounts:
   #       suwayomi:
   #         app:
   #           - path: /home/suwayomi/.local/share/Tachidesk/downloads/mangas
   #             subPath: mangas
   #           - path: /home/suwayomi/.local/share/Tachidesk/downloads/thumbnails
   #             subPath: thumbnails
   #   tmpfs:
   #     type: emptyDir
   #     advancedMounts:
   #       suwayomi:
   #         app:
   #           - path: /home/suwayomi/.local/share/Tachidesk/bin
   #             subPath: bin
   #           - path: /home/suwayomi/.local/share/Tachidesk/logs
   #             subPath: logs
   #           - path: /tmp
   #             subPath: tmp
