apiVersion: v1
kind: Secret
metadata:
    name: suwayomi-config
    namespace: downloads
stringData:
    AUTO_DOWNLOAD_CHAPTERS: ENC[AES256_GCM,data:KwUfCQ==,iv:ntGoiUzTQgAtmFc700e+0Fg11iwDWl9+gUT4WL3s4W8=,tag:mJKtoX2/0k972woExionbw==,type:str]
    UPDATE_EXCLUDE_UNREAD: ENC[AES256_GCM,data:K2f//ts=,iv:34Jnvgv2DS6XZ32sPex7+rAECuPwxvDloFGm8oWo89s=,tag:/eZrFsAUAuknna4DSDsB9A==,type:str]
    UPDATE_EXCLUDE_STARTED: ENC[AES256_GCM,data:985n1V8=,iv:X88pHzPFt9C6wRD046oGmoCW6La/9o/Xnj2AzJbezPk=,tag:j8feF+yjDmtNlQ/SuOK9gA==,type:str]
    UPDATE_EXCLUDE_COMPLETED: ENC[AES256_GCM,data:lM6CnkA=,iv:42Fnpqb0mNptMotw0z2LD+E5jwNNdXBxV3g1iYDqKYc=,tag:5QBEcgJytCQutybrEzYnTw==,type:str]
    UPDATE_MANGA_INFO: ENC[AES256_GCM,data:Qw6+VhI=,iv:Zycp3jt7e13xGjaebBDQKtWYwrlIgZkEy2kUBum2vFU=,tag:l+8sUmIgX/+ms0xZFn5AEA==,type:str]
    DOWNLOAD_AS_CBZ: ENC[AES256_GCM,data:n7IABg==,iv:XwYMCLMR0oQ0I2Ih7TbEbSgsRCa3l0Q3O0EgNejUj3I=,tag:a1qSNiiLSJH9Kz6uSBjpMw==,type:str]
    EXTENSION_REPOS: ENC[AES256_GCM,data:cDF9T1yFdA2Z0mO+Q7QJhQY2xO9hg422pf9UqxmEghn66V2P7FpeyB59mu3nDc9ck0wDibLeqFg2F/tCXjsi9BGlwoTS1sc+pL9sW2XT,iv:lyWCgi8Wgm9f/PjJjHXCYLpLHfymfDIQb6A5b2g6PNM=,tag:J/MwLuufwzG0GgHcv41a4w==,type:str]
    FLARESOLVERR_ENABLED: ENC[AES256_GCM,data:koZy4U8=,iv:3F01LyvlCDxD1ka8xcRMFi5Ar+JSWvdh0o9rggaX9Jk=,tag:gGph3jz+KKuq5j0n2CoyzA==,type:str]
    FLARESOLVERR_URL: ENC[AES256_GCM,data:5EwTzjDF3II/1k8XDpeWcQxZcnQtxWiwynp9a/YyUvBa,iv:8oF9YihlyP9REe0cdz8vz3DW3bQBszbqNfoG/jKQPJ0=,tag:wZKNFa0jU75/7FpeXWz4KQ==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T11:41:50Z"
    mac: ENC[AES256_GCM,data:XAT6R75ddb59qEBBAa8qvkqiKfHkYh1coOu7j9KelpcHv/uLlu0wEtTmUVs/+V2JMs78sAywfHouUL3CWgN0r/3XrHO+rB4+hio9IDffgK4uYLy6XnP5/+ifC0P/E2BXJd7M9lzkSTV0fwqBBxZk8tXO2POrPZPmJfFVTEYKF68=,iv:2KpnKqvsEr//JELGW6+9HRQg6xZ4BF9C4HUmmySmyq0=,tag:TFPfGsG/Mw5oTZu18Gbdwg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
