apiVersion: v1
kind: Secret
metadata:
    name: suwayomi-config
    namespace: downloads
stringData:
    TZ: ENC[AES256_GCM,data:icbxEl6uvbgrwynJkQ==,iv:YcCPUM+HWhB9iQwPaM8L4YU+XDmH25WvbSc/hSmOV4M=,tag:0Rjh9DSxQvhUgeIDNUWahA==,type:str]
    UPDATE_EXCLUDE_UNREAD: ENC[AES256_GCM,data:w/KirkI=,iv:EZGEw2EiuG5qAwvw0ZuYJQ+wCGmRqst1JZ/uPdeAEEI=,tag:1gAbDn0g+t+hG+FePuNNnA==,type:str]
    UPDATE_EXCLUDE_STARTED: ENC[AES256_GCM,data:6cSniew=,iv:dTnWGl5YOUN6Qrf63/ppz+YjHywfQsOBGOFb3MJ6R3I=,tag:pIMKG9q2EyvkyLsfx6ZhWQ==,type:str]
    UPDATE_EXCLUDE_COMPLETED: ENC[AES256_GCM,data:1xGcsJ4=,iv:1s52w+rkCOyW8tx6PIsN7xaQi3SPSiH17b79GLV3ocU=,tag:p40Rd8LCvwYLX49CrZ0exA==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T22:26:53Z"
    mac: ENC[AES256_GCM,data:WV2kwwvJG+QD8YW1b4omL6DAHTs1/aB2VdLB81nYZDB937M3hSMDMhe1NbiUao9OLoIMoWThJEAcZfLFNJtO22WwKrVKaKp9V8xwtDHrHddwzhJPMiLQDFkRhFvXDGg0MEecyc7D07RTOUwyfM//kJD7Nx7QBqTVC0ZPLKghHlU=,iv:KcjkkLBnMZz295Jx7QKqU10naS50c72IoXCNplFUZ9o=,tag:gyfDFpt1I3UfnAcY1l/eMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
