apiVersion: v1
kind: Secret
metadata:
    name: suwayomi-config
    namespace: downloads
stringData: []
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T12:21:26Z"
    mac: ENC[AES256_GCM,data:/QE0eFGveB+to5Gljn2Eg97Hqvjkqdg7Stc12AjQcfWgulO5NPrdL2BXqC1KEe2G9jSTu/DLaXAa5ZtUukWROkvoKtEM5JvmtooLg02Bs8kHMOkfEaBLmRcEyoIj7bw1FYMIUr2bJxL8arz3K9cfEwW7JKyqPi5JZfKvnyvBVRE=,iv:HVhUAqesmy++LeQuA9FCF0acFYfteVRzEsUHGbSQ3gk=,tag:Wv1jzC2xSXy+2HKO0LYzsA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
