---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
  - ../../components/sops
resources:
  - ./nfs-pvcs/ks.yaml
  - ./samba/ks.yaml
  - ./komga/ks.yaml
  - ./syncthing/ks.yaml
