apiVersion: v1
kind: Secret
metadata:
    name: vpn-gateway-config
    namespace: vpn-gateway
stringData:
    TZ: ENC[AES256_GCM,data:SpPI6u1i30jX2Vz8VQ==,iv:dwS/PAICIL9qDjfKakrYv/rYD0v3GdfOFzyQYSIuBmA=,tag:dODfZoCl+/UCL+ImTXtfvw==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:eaG4+bLYv4Yd,iv:Eetst4mH5Cn2/oHcsfjy3bS9YrZGS3kYhDjxFQGZSgA=,tag:9mCm9QBdxaqyY3fo0DeJYQ==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:6gTiRRfPKg==,iv:sKBiQRs/fmVXsN17jZfbJUiDK1tkMv+1hDO7UvphLsQ=,tag:TnGSSOy14SfN869Hl9xCBg==,type:str]
    SERVER_REGIONS: ENC[AES256_GCM,data:38shNaTJ,iv:R4OYnqdZedVqIXZW5LelYgy1wdcg/DArn2NYo/hbcJ4=,tag:TE/ruFnlyvt2af5Vm8MkuQ==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:PtfyqmoLzqXbWyrtJjfVEuuQmwtoVnfp7fhR8llF7CnB9MCJEjStOV36Jd4=,iv:dZ180TPVcydTlzfYENgzvgkD0svQiO0XmEJpM5EAYB8=,tag:v7uoxQG7wtBMRH05f4QR8A==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:e+mkSJ9fBL4vEoWy,iv:Gdy/mhCXFJ4nHA7lHlVDW/cIas36fjpzOgkpnMvPp6k=,tag:dsrLMaBLJBfSMF5BsuGjaA==,type:str]
    FIREWALL_DEBUG: ENC[AES256_GCM,data:TrGEAw==,iv:0AkomPKotOerjCJTmwOzidFbCqmSQMVsld84ApOnMJY=,tag:mpJ04UIU1jjB7+X4+8RfNQ==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-08T23:27:19Z"
    mac: ENC[AES256_GCM,data:pq0glmc7Xh0WSCrIdoQ8RoHDV229FKGo8RCCYjoe1HkHflFO0U/f+AQ/WgjsIkFtRuw4e+TjwNIqXaBF+2+H9v+15FY2fwxb/bCOQLnd5p60GbMucezi0vnFPJMqR9pCqqUl5lu8qBFIeTAZanf7RZqFZhJEmGL+ij2p9+TJtYA=,iv:A0lZThBMdV3csfJh7FtOfCtu0avHUflzHJ4YguoJltY=,tag:VDmldBB4H44GK+wCdeRIbA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: gluetun
    namespace: vpn-gateway
stringData:
    samba.yaml: ENC[AES256_GCM,data:f6RsGEq9cO1i5loBvbaERqzhWNVSNkJgpq0Iqcma9GVQJGuOcNPKKT+9q87ZxNVfCUTE6IdlgL7arxmq1mjv8VXRZgQzRde4ov7f39Yuc/upeBr5wZ2R9so819CLWTiqiy8Ym1jEVO0jh0Ef84OHcpZALcLbT5NlJxVR4GL39iGdeEXQiFs/ArfzSgb7VW7eToJZX+ujm6DxNyq5pZUF0NDyeX74tJmWtO10ZFdOzQv2HCZSLCzdtXzovFSnIj3jqzZysyCUed1kM11y/TVjz/+E3MAXXsOy8KZB+I1NsokBtNLOnQ==,iv:7byxfwfiFeK37umCkFTnJyuV94ox0UskKMgP8DMl4MQ=,tag:5DKEM2xVt8bJ1AcYgNSB2g==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-08T23:27:19Z"
    mac: ENC[AES256_GCM,data:pq0glmc7Xh0WSCrIdoQ8RoHDV229FKGo8RCCYjoe1HkHflFO0U/f+AQ/WgjsIkFtRuw4e+TjwNIqXaBF+2+H9v+15FY2fwxb/bCOQLnd5p60GbMucezi0vnFPJMqR9pCqqUl5lu8qBFIeTAZanf7RZqFZhJEmGL+ij2p9+TJtYA=,iv:A0lZThBMdV3csfJh7FtOfCtu0avHUflzHJ4YguoJltY=,tag:VDmldBB4H44GK+wCdeRIbA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
