apiVersion: v1
kind: Secret
metadata:
    name: vpn-gateway-config
    namespace: vpn-gateway
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:eaG4+bLYv4Yd,iv:Eetst4mH5Cn2/oHcsfjy3bS9YrZGS3kYhDjxFQGZSgA=,tag:9mCm9QBdxaqyY3fo0DeJYQ==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:6gTiRRfPKg==,iv:sKBiQRs/fmVXsN17jZfbJUiDK1tkMv+1hDO7UvphLsQ=,tag:TnGSSOy14SfN869Hl9xCBg==,type:str]
    SERVER_REGIONS: ENC[AES256_GCM,data:DvoOe3q1OmE=,iv:dJxC+COwT91b4LpyCrIWNUXUpLvibStBQOASJxXNh/k=,tag:BeckaEDwUqGvpw1w043T9w==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:PtfyqmoLzqXbWyrtJjfVEuuQmwtoVnfp7fhR8llF7CnB9MCJEjStOV36Jd4=,iv:dZ180TPVcydTlzfYENgzvgkD0svQiO0XmEJpM5EAYB8=,tag:v7uoxQG7wtBMRH05f4QR8A==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:e+mkSJ9fBL4vEoWy,iv:Gdy/mhCXFJ4nHA7lHlVDW/cIas36fjpzOgkpnMvPp6k=,tag:dsrLMaBLJBfSMF5BsuGjaA==,type:str]
    WIREGUARD_ENDPOINT_PORT: ENC[AES256_GCM,data:6JosbLI=,iv:m531vjhNXZWcrKxgPzGruDPBd9LTzIbUWWrCNT/sboE=,tag:nV2shZNBZmi1xRCiVi3gqg==,type:str]
    WIREGUARD_MTU: ENC[AES256_GCM,data:4UuTiQ==,iv:ikMhYEmN6c3/Ar3t1oHA/1CVdTaFZqVxgSp8IMA4yr8=,tag:V4FqFQNiW+4iwU8rCNS4FA==,type:str]
    FIREWALL_DEBUG: ENC[AES256_GCM,data:TrGEAw==,iv:0AkomPKotOerjCJTmwOzidFbCqmSQMVsld84ApOnMJY=,tag:mpJ04UIU1jjB7+X4+8RfNQ==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T13:15:17Z"
    mac: ENC[AES256_GCM,data:ClrhsV5M8chkmEiCF5RpNIeab1m5AX3QlQ0xaxqghZyZN4CG/jHnyX9qgQotRSMGXjax3M4PQ+c4bcPi1tVMAH6CF92YMbxNc8TR+HDB1SEXmnWfkUpXSsSUpVIvhzUvPqg4NZO2W87m3lZ6gOaGD3oPmBrJZnzJrKjvqLvPpXQ=,iv:CSGAOXREUEIpsAnya8AAq89zAzhRakZ195M2GRJtIzs=,tag:tfUaTbgWVWN+Lbb1fKdC3g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
