apiVersion: v1
kind: Secret
metadata:
    name: vpn-gateway-config
    namespace: vpn-gateway
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:eaG4+bLYv4Yd,iv:Eetst4mH5Cn2/oHcsfjy3bS9YrZGS3kYhDjxFQGZSgA=,tag:9mCm9QBdxaqyY3fo0DeJYQ==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:51Q0r6+hjQ==,iv:dXiBvDXt2KnM/rIkDBt/owA/dBg0AYrybZb8vZq3E50=,tag:fnDyfK79zA38XG1lK5ZRyA==,type:str]
    SERVER_REGIONS: ENC[AES256_GCM,data:Hanm+kRD,iv:2xOZk+Dkb66DK9RCNAGaRsRQE9uKyh2RRg3KbRCyTcY=,tag:6AsRCzhGqKThPVV7D0nRgQ==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:zv2CDy5mF2+lOjN7Rw==,iv:atORvoZd/937wzT/wxeiA2ZJYUUSL3iZgkEc30JIvjo=,tag:3vEIm6j9DEo1Hj2+G/EKeA==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:PtfyqmoLzqXbWyrtJjfVEuuQmwtoVnfp7fhR8llF7CnB9MCJEjStOV36Jd4=,iv:dZ180TPVcydTlzfYENgzvgkD0svQiO0XmEJpM5EAYB8=,tag:v7uoxQG7wtBMRH05f4QR8A==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:e+mkSJ9fBL4vEoWy,iv:Gdy/mhCXFJ4nHA7lHlVDW/cIas36fjpzOgkpnMvPp6k=,tag:dsrLMaBLJBfSMF5BsuGjaA==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T21:56:16Z"
    mac: ENC[AES256_GCM,data:jeBJU1XEWNqY5OHLHAZghxquX7QiUOJzM7ElJ9TeRslVDWWWHQNfuuGdfsy2MLDprtG5g3WOQyAbxNr0YzA+86cG1iya0qDr8kQmaIUPLph+9u7SQn3W1DWsMB2qptchAV7zfPz5q20BrJyxMGxydJLdXqpMBqL4oYOxxBRdxmM=,iv:6CGjVSXBrmMc9priBpP3jRposUYdXtl2oFqHYpB9hR0=,tag:OuwyNABQ9hjZq0/ZqD3gag==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
