apiVersion: v1
kind: Secret
metadata:
    name: suwayomi-config
    namespace: downloads
stringData:
    TZ: ENC[AES256_GCM,data:GxisaoTKCvWsUkrL5w==,iv:CoeBkZSTS6yk0LX4jq8wFAw+eMl7AshlsmeVRoERz1w=,tag:5M6M1uXaqIilqkiBuBFQAA==,type:str]
    WEB_UI_CHANNEL: ENC[AES256_GCM,data:7MHbEWvu0Q==,iv:GUihk3VGq6whjvF0sh9qJtz3jMQQSSgz/nV/t0EdWnc=,tag:8s1ucOR3kBAX1Ai69SKMwg==,type:str]
    AUTO_DOWNLOAD_CHAPTERS: ENC[AES256_GCM,data:ifdJYw==,iv:7uVpbkkG+XlftOGKtz5euAAeZ40F0bzOJqY0l6uhgCk=,tag:ycnfBozBbWHOmFrXA/gsjQ==,type:bool]
    UPDATE_EXCLUDE_UNREAD: ENC[AES256_GCM,data:plZXuXA=,iv:myY1aZsBZdicQ1o+Kuhwa3Hekq3VkhJZU10yLy5hrsg=,tag:BTnzUZxH0lHw6TVxuBwp2A==,type:bool]
    UPDATE_EXCLUDE_STARTED: ENC[AES256_GCM,data:NQJoR9w=,iv:nGqjp4erCdoAdyRVYrxknhbRE/ul06d7zY3idhRK3gQ=,tag:WvE+zrl+YBBV/KJtAEl8+Q==,type:bool]
    UPDATE_EXCLUDE_COMPLETED: ENC[AES256_GCM,data:P6Pz4Ys=,iv:dx6YPSxbhK4oXwpK68GhF3NZt0PDoIlFy74V41Oe80c=,tag:HIBQTm8v9RuoAUj06ItKig==,type:bool]
    UPDATE_MANGA_INFO: ENC[AES256_GCM,data:7vhudvw=,iv:yL2c0c8pGGD2a5p6WYA+oCXGoobX0tLNmTtKBljUvXw=,tag:+Vp9sB0O2yUGh2XoCC6B5Q==,type:bool]
    DOWNLOAD_AS_CBZ: ENC[AES256_GCM,data:Ds3Q6A==,iv:DR0SoMsxUVLK58aThzCt89gzVVFBT9h7Evt0jnCji58=,tag:r2eosvk3tA8HfpoeYvxzew==,type:bool]
    EXTENSION_REPOS: ENC[AES256_GCM,data:cDF9T1yFdA2Z0mO+Q7QJhQY2xO9hg422pf9UqxmEghn66V2P7FpeyB59mu3nDc9ck0wDibLeqFg2F/tCXjsi9BGlwoTS1sc+pL9sW2XT,iv:lyWCgi8Wgm9f/PjJjHXCYLpLHfymfDIQb6A5b2g6PNM=,tag:J/MwLuufwzG0GgHcv41a4w==,type:str]
    FLARESOLVERR_ENABLED: ENC[AES256_GCM,data:wSwZ9Ac=,iv:TwoJ72EwyHglqJoiYxt/EQ1GS8YK+d5bPpqAPkFHz/E=,tag:pd3rQGiqZPcmSOdSNr7Paw==,type:bool]
    FLARESOLVERR_URL: ENC[AES256_GCM,data:/cTkv/J2kPwNmxofmrZh6YKZmlMyTalJQq3NWPQ=,iv:6Gyxt70PtuLX7cqRNosVP1b5XMjy1OeuBBpTZtsvm7o=,tag:xdGq8GlzwE4hoXDlIuzZvw==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T22:47:07Z"
    mac: ENC[AES256_GCM,data:+KSf26o7YTSjpFvXWsvPl/Vyaz3j1xiTWgOJsdMznOypNy81zXDqpDGbdDe1J6d26rbDne4ObH7ppBHg6Z2UAH6axBdj5V78kUAyxaqtzXPqKVU7XAnwqcOvVVXdwricFd9+zz6So1hNrrY04yo3fxuIfhs4/Nsk2P7NORzrTfE=,iv:UGqD5DSLT6+8iCXcdSWHBVD8pEJOyNGzWM+ichsElWY=,tag:G4yaJGfYAZfrvSL86RA1kA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
