apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:aTsy91iXCSRw9CXsOcUHQ29bmeMhBQqtJt+ASJrEUyFo730uQlOaAA==,iv:s4mPt0CUBXPqxFqZ2xkRtuytBxDVX9k+AQyI0QuRBpE=,tag:eyboPXvfpC7QxnRgKEKy5w==,type:str]
sops:
  age:
    - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcXMxR0UydGM2TVgwc3Yx
        RndpYWxOcklQWDI1cjFVUXA4MHFWeXR0MWhFCjliS0svM2twNkRrQmw1RUFsdnZX
        NmhndUNVZ0xmMkZ6V2pqUnVVRlRJelkKLS0tIEJDei8rZTh2Z2ZkQmdkczA3VFVO
        MVBOWVBWd0JHKzN5NS9nZDA4Mkx6M1UK2kgtOSfHQlDvQXNpNsM30Dt2MWTcKoVt
        G35vlrsf6YQE2yAcgcrb3PwfVThTlll/Ll9VtLUXBMTRZFDSxE54aw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T18:45:11Z"
  mac: ENC[AES256_GCM,data:aAwTBQDfl+omZBGvUe4LLlFeoYCapj4EgNT6rDP7e1GMUE8BA6O2Vov0TuHzlWNAkHqfCNFTyWVq11hEhTSHQ6U0PsbTNG9vhP07vz6n9RHigXIIDnNLJ9bhNQQzIeI7pq1b1F49XuauUOIqbJg6taIQq1S6W4Me7/wPlCBBGQw=,iv:etk3hufkxcIbBBF2L6+npAGWsuDpAMo/X6fZhiZIarw=,tag:GcukKCHisuI5UcYoezT6eg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
