apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ECOBvgcjNLvC,iv:VbeURpCN/6a+Zl+OPcUQVj2nnvTgdv4Y1M5tfdRYZgg=,tag:haK8u6GhB34qkVfAh9ebWQ==,type:str]
sops:
  age:
    - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTVZjN0tzUHdkVXhQcXFV
        b3FvSG9Yc3pTMEFHUWpBRUtrclZoaHBJdEdvClc2QUlGQkxvN0l0UnR4T1NPdmZv
        WnA2TGlQUVl0VWs2aW5GK2tYaEFJNE0KLS0tIGMyWVh6Rm80R0hZUkVzQi9GODZ4
        Z0ZodzYyRVZIelJBcWZ3VlFaSFAwRVEKUCg78GmMeL25hyRxbm+fCkx3v/kaarYi
        rexhNZdi6CXi7k7i17fp+QePxtMEEZNeCldjatZOzID4PR3yOXKshQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T18:45:11Z"
  mac: ENC[AES256_GCM,data:3BcOgSstrFqZj61gjIovOWq1zcuvUNNx2VswjtxmQlC0YGRWKkv190Nj0PtG5RzX1YrDgxtHhTiJtEEPpEeuwxbT3tyzM3Vvp8VAQDnK+G4or9d8VOBvIJa8PzockkbXkQXBSnuW41xQbmt2QxuLc2TPfbie+YzeA3o+z8Mbu6E=,iv:RM9+0ixcT8mJmWPcB1rAo2WbxULjbCutUBB81DfcvQI=,tag:mIDo2AG0ZtlD20BBwwCxWA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
