apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secret
    namespace: database
stringData:
    PGADMIN_PASSWORD: ENC[AES256_GCM,data:Eh71nUSjT+CsxPI=,iv:tLoncPCvmiPxmhi2Iym+adkg103Ot/chHWiuFmFyO8A=,tag:IIq0xbKm2SNUOdDcfwm3oA==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T22:29:26Z"
    mac: ENC[AES256_GCM,data:Q87SRjbX9HTVYZeMCviq5wLRxgCSw1jS3dgL5b4C0RsX/aOqdp0/saLSytEEN6hZEkveuREFGBm+ZMqz74xbs9ft5ohXVI9fDMNqoxU2UcfFlCJuNoJpcxuz1jCB22baKPc0q2kholGl85X5/xOWwxUqdEJCa6LxZfEpwL5fnNk=,iv:AHeOmxjDVKu2GOLCR5fa9ePqwk546G9nbPn1b6yY4xc=,tag:wKzqHCtbhPlZP/XOsJSEBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
