apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:CZcfuOTKY/DiD2et9snp6LwaYI3TUjX5NVdzc2/Dz5MCnqoB,iv:/itPBQJ5w88RFiIK5S4iAnY8UVUwpXIavQumu9aHhcQ=,tag:BprzVAqsS++Tb3UrnLR3cg==,type:str]
sops:
  age:
    - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNTJBT1JQb3A4dFdUMWJJ
        ZTlMYjRPUjJObHQxQk5aTTBSVEVIcVpHUHpJCmw2aXFSSC8zVUpzVmVTcG5HeU1J
        OHN2QlAzZlJQbXh2VnBpZXZaaFVCVVkKLS0tIFRhNWc5bTVWNjJOa0sxbTh6NVky
        R1lOV05iU25rZENvWkFmbjJ4ZU8vaDgKOODPnYpBCdv7EbMjJxlrsQLGZL572HJN
        t215gQlJkdpw4/yzEqyCHCpwkIWFKqq1/NMEJ7gEDHhjrFgiLtBxrg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T18:45:11Z"
  mac: ENC[AES256_GCM,data:mobXKZym0OJgyN4xCN0FSgLovIkuRKrtaKrorC4drGh93+3s6zZdqSa7r6RYPX1PQxO3sNWfgDSkyWANAVPzgn0AzpncIb77PFJcO6rKGSfnF1xYsa2y17fSrxVI44j7u5oJA20OzwxbIdQAJrGT7g1j1x3mVc9AthnstgCFxw8=,iv:f3LoStbu7Pk58vTbodVaUab0Yk8OusNVtK60K2eM1WQ=,tag:LEj17/XqvPtq0mfe9jLSGg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
