---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./linstorcluster.yaml
  - ./certificate.yaml
  - ./httproute.yaml
  - ./issuer.yaml
  - ./linstor-zone-a-config.yaml
  - ./linstor-zone-b-config.yaml
  - ./talos-override.yaml