apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:vqrW/Yy/KwCU0paKe1OU+u3BDOTvSb1OVyYF8z2Oa2cFwPLjkAg4YUIQTBMQSLtUqUkkzgdVeQHs5TOAHAN12vcVYiBy59y/RNa40nEdEhw2EnMhDNIR9ur6xpn8lUx1fnu6ZHvVJO9oKMdvTRk7AlkHULlH3Ff5FFWp7GrGjfvPWgTvkGJlall1vskyPFyxYGB+TbOqYF9HbegqbgXmRFNUl48HLmrDTq9xL/ErZvgcki5N,iv:07WeTFluV0p7AXK/KQgSy/dAzWCjquD5x0/J6A5RTeA=,tag:aLiQUttjrnalC2k9vacYTw==,type:str]
sops:
  age:
    - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQmVSUFNIdTlLdDBsOVgy
        OVZOay9kMEFNUEtSS2p2SDdFMU9Ucmk5am1jCjBtR0g1N21aN0dNejl3bEN4TDFt
        Qk10Z3FYYjl2NzRPMExJN3NzVXg4Q1EKLS0tIHQwRUltWEdDZmtwNTFrTXR2VWFU
        TFJqUHVMcTBBY2JoTTljVWRwV0ZES2sKBrPtRLBhqxKP+rdWp9IId4E0Sv+77P83
        KixilQRpvh34iXUPwnwanlAT95/cgOmDksTWaVbQ9CGVV1c6QP8LLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T18:45:11Z"
  mac: ENC[AES256_GCM,data:3mEKZ7htfTGbwyqxPCnf6b83ga0NAWDUUJGu0gQ+W/uiyUT7CaBUavARUm/Ej0u0giSasO5t9HAji08plpG2aTx0kCKe/RxWbkwHijgd0koa16E3p2+xjPXjSr5IwQGXAivf97r8B+kEobFEkTpYZ4upKx2uy1PMdBVvmLZirJI=,iv:G6u/E2S9p4Dbfeoy67IwGSJBMF4wgW/M7OFxfQRCqzI=,tag:MaZnNZC6uotqYQSk5dn5fg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
