---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tranga
spec:
  chartRef:
    kind: OCIRepository
    name: komga
  interval: 15m
  values:
    controllers:
      tranga-website:
        containers:
          app:
            image:
              repository: glax/tranga-website
              tag: Server-V2
            ports:
              - name: http
                containerPort: 80
            env:
              API_URL: http://tranga-api:6531

    service:
      tranga-website:
        controller: tranga-website
        ports:
          http:
            port: 80
