apiVersion: v1
kind: Secret
metadata:
    name: samba
    namespace: media
stringData:
    samba.yaml: ENC[AES256_GCM,data:QCdD0XcrP0NG0TLWooaVdkTV1D66O7XzkYCth51F/FP3kpyF/dRQEc7KN/J8mtfihUhV7RqIZzvTCZ2cwLYfIeD4iTansKDfCEsrJHstewRcAIfzsFNjjv9o6CevzXCSMBolJIwK4XYc6ZiPihnDHgCr61uuXEukUVYrl4WM59zFqohmc5lA89CaGfr1g0E2vpAxc2lyXbcx6KMzij0BssV5A2VWELT/DLhS+74kjFqEP0egHsYk2S3pPaeaXf2ltELEneIxlyCO4U1qOQtfWo0MrVOBazti2YNCQpfABYlr8/DR+bN3YJZUgHkvcgsUlRFY43zU2ppHvvXMjy3BrNHJJG3Akz6h1ViPUw21QLNF4X/NY4BqZ7qMf+jGO2FLdyEqis1+VRrb+nCkxQSDYd7f/KzKFNwyMIPDqVyU0SGyRS9w+/lvNOdho+yjk/7MBPqVMU5d0jcSbl8C9Y/fstYH8s2iSPE2Ts57yOrAkpi4dfSYpdKJA4vOPea8Y4O/BDWx03i8epNcrTYz+0eDb7eHwBlpcLgSqgdCMtwq6vaUcXXViVbZnGVWiyFdH/jw1QU+Ra4krOV6dwgj1nYRgFJF3BCyRIGJBi5svLmHMWF6aLOvyFDSgh2UjcGqs3q/DPQ9vZiEEi8c/IYXg0HFSHqH+3oyvLVrVAtdBP56,iv:3C/styDK4V8ZS0z9msJOH4uK0ZO4feRF0O1l9kfYxxk=,tag:LDwkgYY5kBgRbMNO81/Xzg==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T23:56:03Z"
    mac: ENC[AES256_GCM,data:S4MqWMqpesFYv8XzqvwOarcGaPIbOYTDcUO33CUzc19cQP3DxZYcg4Ll2EeHxCBWoJ4/qN4vayyow7ixiWzL+kK2xRaQWde0cM+6O0/hVucQ5udFv4Mjhwrpre7nisDJtqtuQS7FI0+U9cZNVTc51tK75heCXCT9m8s5ZESugUM=,iv:133wnaLUVhsaw58uQwffToXPcti0qH4r3XVm0W2nLw4=,tag:RxOve6/Gh4RiYQrKg3sEJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
