apiVersion: v1
kind: Secret
metadata:
    name: samba
    namespace: media
stringData:
    samba.yaml: ENC[AES256_GCM,data:US9Rf1RmVqqca+19y5rTxkn2NpDLzlhmyCY1f5N4lTAYzx4cmyEQhe0uU92TRzbhNDOt2o3U/kGTt497zX2zGqYj2qx4CMKyFC15/V09GDg8a/xCLx78iNUWk/921KkgctNqdSHpB3C1e/GfqvBJ7gQhQrhBTRzm0fhNlZUUb4rv1gCPAWHsQeYRQ22TSegNKyvRVFKGjZ93afj7sCdKYQOryG0dF3Bkl1DT+K+UyjIJXXryODgkNgqSp1lmjUFng0tQ2AbpEI895hMF6MXskDkzwLU+6/9jlvtHz1aEXYHsow2uLd22kDTYoxWTt8Pg/ACLcl4m5tU9BpEYW2nRd8CW9s6dqQFj2lpPv1D7XQnp0eVkLpCjI+NYY0GeK/tazqXWW+PDMHIKGcnkprli95dzhTj6fuD6LHpqdt7IykkKsjWoL/HWZDVkyWQKCNdD8XBFPn+f+m28tZ6VW1JgXCPqevdY/9uYCxMwXyPeYmYCDmI9u2p4gk5JDbjf947hswR5+5T1paa3nCAMa128T+hFQ/2qAfMlnL+MCUiFolMPbDmVpdLbWPpyyrLr+nNsxjX+Q1udMsoTazdDV68UimJCVKK22LDeG6AwrWL0XWLDG4SF7mdS5/xIdB8lvI9TyXQ=,iv:Jimm7WHSfQJu8NZcECj5nALwW7wOexmdjHHZIUT04sQ=,tag:pHqgeHaFlH0No3nN25vjog==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T23:47:03Z"
    mac: ENC[AES256_GCM,data:iuxEEWtzu8+0reXvab8M87hOswLWCjbNgco7d0MEIZ0uXDcYZt05l349qRWf6eYfB5+Jo+V7qVqkZp5GYlDkNBunYe51lX0G5gA3r7Q1QZPV10rJjQAzNQeecTqNWXPViqyvWOe84tehak2qmOxdDsNaqOfJxAysO+3hAW1lgW8=,iv:epJpcWbV9cXSV8WKkDPZRxUfruaRBShW+U6oyKjWyXg=,tag:VCVSALxipav+iqTDF/EmKg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
