apiVersion: v1
kind: Secret
metadata:
    name: samba
    namespace: media
stringData:
    samba.yaml: ENC[AES256_GCM,data:qERV8T5tJeeDVM4frZ/UvF20X3UAq761emK3WonUnIPmMrBfFU5ldhROOm9BOZjKhEhb8EOpPRgADfGfmVsEs8b/PkWhwaxYTJwJWipis6YQeiMdstbcCIFgCkI2M2n7hisCTPov+2l6tvyIfqe6VgcsHnBXMx4XMukTj3UoqT6HL7Cg3CDbswka5KzjpMiQq2rx8o7XtfCpSyE8Xmm7yqmgZBECBNnyaW/ISOJo9XUuGPlRActlkSgkWKhkSy/S1JawjU8UuzxuElkcIzqh9gw3JnZ/DYsT9V4bsRZbyBl1MzpXOuPMEnHtxQf/LF/Jo+Vol+4a2uUVFKwdGGZVHijPxvYcjlV3jdi6Pe9/BFKn5f7nRDSi/bRZKiKtQxHzb6AxnseshfQRaUSVxjdQNcFTZKyVmiBkThGmswxiLw+eXOpSU0Qq53ecIH6Qag07,iv:iYBUq9//Moyv/R8vrQa9i/v7k0uUYlQ19Qe51cLF8eI=,tag:Hj1fH8I640dJ5pk+U1ibuA==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T22:45:33Z"
    mac: ENC[AES256_GCM,data:K9bsUKF+pb4OmYwoe/OkauF+CKDoZwYlVBIP8IyBPR5pU6RknDrZizg5ImIEj4a+hYIhvlwDkWRaTvnBT2dNFAIXvpsLTKxDzvAC+51Wv4eQnnbsCtV9N3f0DiNv7E6h8tmE09s3DxGIXhO4kgLEpt8ceFp75unVn2qCwfgJaGI=,iv:RroXuBEemovarDbN1x4ip7M73bWV35d7OGHmYFNDskc=,tag:AaHCM6XqJfp54xpeE2T+Ag==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
