apiVersion: v1
kind: Secret
metadata:
    name: samba
    namespace: media
stringData:
    samba.yaml: ENC[AES256_GCM,data:acrS7U2k2uXX4xrHiG9iEUolF9JWuKK37xB2HZxpfNrpA6/fvkv1/PUSjKUkn2a5a4yBhEAIV55CWHAL8U+HK881SgCbZDPLQQ0+LEisYe+1/wLb5JCiG2gHTTgiWPO9bOduPeC5icupP7lQ1IBbL2CtuFZ6hlcSGkvEjYqkeWc2ZBb0RxgEVcOSM/3Oal8lUykUCaDc4+dCD7RZPtkkyiTkxnEWU/5AlPJ2tgFLAiTtuSlAyOT1KPBX8rQ+JCp6ukKG7tGabEgudXhwGoiNjXytDr9hHcRju3tuw12IfXzccIkXlj8r4FCieAhP640EPh5+sNSEqzp9NGrf95dKuzsNDDlLFpdD+OumGgoVVYXhysbWrZTz13edtW4=,iv:T2Zf6thiTuQTC20y9ENJPCO2cyDYmBZA8AcoB/GBBx4=,tag:T71UtoumxyyhirhD+DRPhQ==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T22:00:42Z"
    mac: ENC[AES256_GCM,data:KCJG1+itjHhD9zlEHQAzE7NzrDw4+E9duuVBixL01KvjMbLBDogxTr1tEjjlPR1rmuEnENFoT5It9LiAJdCQ4ODLkbJTx/FfIRV3l9z6I5pAE+MW+sNxcrobsGOAJotGL/hdds7xmwpaEqHcrIXfe5QKVAFKAasp/WTT+oxUfwA=,iv:19v8OC56cbrupzJ9dygvhAAGaHOB+Nxz5V7OSu7Kn3I=,tag:HhDD9D7BobhvFqqYyH8yAA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
