apiVersion: v1
kind: Secret
metadata:
    name: samba
    namespace: media
stringData:
    samba.yaml: ENC[AES256_GCM,data:Q7tOvfOE+0fHIpytgaDoBOGn7628RBm3ab76no2KftH9OFSnCYVInELM1dnIqtKVeZ+cfP+lX2nlYzOy7ykBTlVloIFsKyH1xEAqlJKqheMucFNEpnq0mH6lp6huKxD7xEHvf2fCFIP+oEbjrI+eZ2qxbDExv/otruIjaPGbl5Pli0pMlBRvskSZa2w3L5u1Fb1K5IpOcX3NpqidK9WOGvtfuj0mSTMnUVtmDQ4xO8C6Me2u73QU5J3UbaGnBOHV3KcbkNxwLvm4a6rZHzhs2KNGg15hWiMt/0xZR/b5Yg7nMSR0QAbiGFq8QZLKFWGNPV/gQ8O5z/8+EelgaHiA+G8sTtcX/OCoziLatBGRtp/3eAcx3ziDkaN7qUvtax8z0BIju5ngmA3cS7B0EWporHpv5k7kWTCmq+pIkpl6qaG3X9vJFzUZlEgk4CGQwXyUqGiafEvILjrVYWtjpQqpR0eH8AY5MoiACySzt3EIHt7M+k7FlpkxOFPper29K3ZJmFtOEipVUXT74Co3iaFeYBOJTerjMRHfCLkBJAa/jYArA0q7XJT3G9BI8phoBa0jrpcjDsl6/PlJHLiZGDTUio//8kawcHI1+AoqNNmawEpIYGowaZCKWM2x51oqvuqKKe4FsbZcRGWD1dEW/Iapqk5CKiCTjUDBxZY2i4j9+KiMUGyUkyAV2o4OyQtTstA=,iv:4mC2PFErChlKcama6y6FxiZZkwEpqUGNf5J4ae1Gt5g=,tag:S8PNlYV8AzLciJa2WvREow==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T18:38:12Z"
    mac: ENC[AES256_GCM,data:AwlHUgLa7/y3Z1W37+FFksZFMlVg+Wa0nFTB40eXGjmlD1JQLKGQ3Nvz9qQo6c94ry0yvmZf8QiruZxKayrHq1jgiUgUOZo4ToU5zXhTm02d4YCJD9ZQOlDzj9OPa9DaZEbZ9nG/wkxvKV/C/xJVnu9JCHIxsOz8vGha9zGBUSs=,iv:VfKm9giZYG9wcRyH/seZaDChN0O6GEijlgJ6PXJk84g=,tag:pj+u8b0idXe8N0TS5j41Nw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
