apiVersion: v1
kind: Secret
metadata:
    name: samba
    namespace: media
stringData:
    samba.yaml: ENC[AES256_GCM,data:4UjyK8UxuuvE4XOlb7NkJlYSDTmkv0GXci97cXFkvZpIHZKZDGZp+RaIYJuJwu9FsGsVnjifsiYcBDIoSPoXcqbweFYJDWEZtUjKFQuerGKb2JiYWqu7zf8Kt1aXHXXO4mOP7WYhehPsQCkjtlHnD0NSM2wzTY3DU1bMxOO7nyL+DD8lcH6Hd7HGOeuQgqvfEbq02zGAPdrdfgGgX5zaAduSnFhuLyumDsvprRbONxm2oHV4h16ERw0nfDTSXwZya81Qw7Qhx8ZcbivtuJMYVoYQ0rlXS+JYVt+89Av1dslkfGQ2JKmjF+kYmEhhkcaF3hmIvZp/sMpbiCdPJOg/2GIr71fXMhYS6VY9qg4ThL8lvTKGZ0hzf6fg2QPUwviKRUH2AB0QQl9fEkA8LUpmhq6zalOwqc8pZwPtIYaUEwvmj8AYEQQQIdLly7c4HP1jKHCIMpnYQ9TozE6g4dB70m44218MQ24wNdQ4ArlT0r9JxSZx0DPAZoaNPN8Mu9LumWZFsmhH89Xzx2vklxLVP2leSqGYP/Yz3H+xgnR2n1mlXhff+D6TyrwgWzTVVIBFqoL24HGEYdpLXDLXUQCpOrmi9oyFBYLOO7zx8+HcXTwmUn38kfDjkGDqV5HquayM,iv:ag8Lm8a8RUU4hf5a3KraZTSV40fSSpE4g0xoWBXMd1Y=,tag:s854tYoryZEq15WN2MTjlQ==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T23:43:25Z"
    mac: ENC[AES256_GCM,data:OGRgA43lsYrIzi/JqWbpBxQIaf4ujymjt/sCdhJ46jZxh31MGqGiBkBiwUl8dp3V2vY06AANAKHJr5mPd2Xa9GLYEcUjVY14UUC+VJV0TE9HffNoNHW2OM6jJsDHuCFCJaEJslJZrGIhpnY1p3Qazyj9jn9kkACFjVxqNzi7cnQ=,iv:tHdx62zgtsNgNohIs8EWZnG83ekEmQ6reAhIACCBdTY=,tag:JhTRKa/dstPDHWuorTLN1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
