apiVersion: v1
kind: Secret
metadata:
    name: samba
    namespace: media
stringData:
    samba.yaml: ENC[AES256_GCM,data:SW94gaw3VSgxapQHGLFbbER2UD5/wqY6YPq9w5jAQHs1xfM9dKBFCxyKVXJo0d6MlovRfIsCwYYJRS/DFtp7x6/iv6ncE9E4j7jxCHJBfGrHTXAUce0hl6LPKW7pUpltvzQn7Pb5O9Az05X31B1wMoj09tVq71+X9MONuGvuGL/2sO8zF61LOQyH8rpFbDFSDsGcYy6qORLBkLY459rAFWw1sqfG1svkJQHUGblSK3JRGNi/2a3i4hUt7xFsBxDHejVrnz1Z16dgO2CROe8hUXPF5FGDsZwmJoW9E48TV2cOyndGIqeKAs2MC3WhLOO3fdFYU+QEioP7h+7TSOoV14ARdj1Oxax9XHxthczd2QNM4Yqo,iv:Beh9JhcdvPAksTIDwMplAZzE4YqNOhTNPb2dDajNtAo=,tag:0uSVU4Vgfi9TGg/9s1S5OQ==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T22:31:52Z"
    mac: ENC[AES256_GCM,data:8X8Z2UChBup/cRbNELaMtdQJs798XxF1674FHORLgIei8iEzQnz2xaYS4MhASxZWPmL43ulJP6ioBCRjrZ7IVJjNmITWUOPyC0NS3IN+GLLYzKxO4OuExtcMH3vsVEdj+4JArPlx5YRjgkr39LMz7JnSn8PqT83cHubDz+Q0lDI=,iv:sVyOmcG9Co8rLzXVoILtAk8N1a7U7Mk/lATWaTJqdQ8=,tag:cuFtIHFb+znSY0S4W9h6IA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
