apiVersion: v1
kind: Secret
metadata:
    name: samba
    namespace: media
stringData:
    samba.yaml: ENC[AES256_GCM,data:m6BB4GDXOm3dQYMJR4R2VXm1FNNdaWB+N5uNWrF9IsHP59yzwsGft8JU9IVNbbIZToodQQXCZdCBqZA0ZS4n/Dz1JyV/rxOjQLdqajXqxJ/VYDolv50TgQRinjXEgOLLC1QdJSo2WYzHGkCqBO/nPyCizSNmJanjUT6y3MfkoG2jW0mJPI3MbB9H0l1DW/hyx43EYVB3bSdrgi1V96kE9upcXa1wQeYku+XqyhseCTZdZBM5QSI3uWn3b3vt4PN3obud5aQRy9tWVqp8yJZwGd7MbwIUwHDcpbnjn/qaKsDoFnj7pDtYxi47UltBgXtvUrlubMREnaYJwrMOoVTlkBXYfVGzxds0rrhnnmbgA87Pl+1P5oOxTplgsUkKspXnxZUVFqx0Ya53+2EyscwKngtRSCiHqhlXITgVo1Pu/zcclCVTcRjQPzQmTyOewHJnJ0RyJGTS1m+7DcEH2QQF+Vo+PnU5,iv:TD7Q+0Xsuv3UNaJ2pO3j62V6V8ApvOxeM13i+0ZB7DE=,tag:7GXFfKqcn+/qNcnwGXawoA==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T23:14:05Z"
    mac: ENC[AES256_GCM,data:kq7Aby3HBhePC3b3/iS15B31Xvou7AqBas5Pvx5JiuyHyVoK9n3W9F3Dkp3+v8i8Mie1RSI+AnjbU7VV5gAxjpDWi2KaFNSAde1PHo6Kp2Rt38h4cGjhzTJzPPqmBmso8fh2sdk6bgoq58sJ7ohfufW7sXWMyBRsEj7UKFW9F5Y=,iv:Ok8fE9iuXXJUsezC0RxAnJiDMbjiDhUVrG62W3sXH4o=,tag:gD6MRxdRhvvBhs5K8ephww==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
