apiVersion: v1
kind: Secret
metadata:
    name: samba
    namespace: media
stringData:
    samba.yaml: ENC[AES256_GCM,data:anc2Ep1Ro9xXJCbded7cp96BbgIf2SBpJuFpXUCHzXvuskU4QGoZbBEP+z2+19yQo5PK7jI4XzYZniEJktHTWVuIstGIhnpZsAZ2HaSlr+KabtPLrfAekNkmUAqWjXdan1pMK+mBx4Aje7MqC6hVG6O0cHgTFhNgYS6jspqm9V1X5zNSCHy6RihqpaEGVPJwCzzr6sJb+bGzNREZpTMYlpqns4L14QX+pQwEumqH237Ud0/RQTc6CLy3uhg8fX0LdYcfRimUmzwERdXbgN7tyKCYcZOqBnmlX+3qXkgV393WsGFNAPYiNqMFgdmAJUx4umgHd7o38ga6XhGXQ8npOa0GJ6uN1nt90rc1sbyNxyHjd0PtyHBXwQKcbNEOLO+0MIsVPFweKKVZvQVVZNujOsHuk099Cy8rwoMP9GRICdxWFcjLfJOCDZUipBEN9oZgBNgnj7eSffSVoTHWZisbhaN0DP0YxUQHrozbe+mXdWbo16T7Ny6XFCcbJFiuhsRDU21Cjt4KtULl2Q3hEOCPOw21ShQSlOKBofjSdOq1ea6F8LkMw+U8Cf4D/TSp4iLKiEBvfUOd+3hNTF+D3hGPs11bfn6BwX4j+p2uCKhjqiq1rzxVqozHvZscchCS5iqXe/qH9Ps5H/5wDsCN4ugP5pTrWbEZFYZdNcRkK4vj8oQXOzosugWIOeO9oHaYHKBXZNH7kYg=,iv:ism4tpK3p2Xipmp6BmcvTJWqTr/Sw2Ef9W2u/JnM44M=,tag:lxnRSlAGOMgL5h4odmSQBQ==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-05T20:58:40Z"
    mac: ENC[AES256_GCM,data:UnF0N8onn0K4X+OcUc1q8Tk32yR6LuJU4Hh82A7OaQsEtln0oafKW4xxOF6AAwvpUsbVLiMkgjNgd/UYHrFV15e/5Y4KKyG0hTEcL6EVNeb8OrL6m++Hvr9H+sIriraIEGjfr8ozWML3fs+LFIYoReeLAwG0FXXjNtDAyXfnSCw=,iv:SHhEWZKJ1uVpJfMFKdIzzaTKV4mBGg6U6xbc5uPzY8A=,tag:IEGpMyuC/tI8K7m3jjoMOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
