apiVersion: v1
kind: Secret
metadata:
    name: samba
    namespace: media
stringData:
    samba.yaml: ENC[AES256_GCM,data:3kPYeXXYcWjEqt/ILQj2BAj1ogYyT0bU0yrHYyzdOv5wP+4SFjIz4JZqE3BfqZkjYFtIDRpkzSF81kkYFN268mXRqlIlNY8c1PoMqyneFUhowYfkn4Nri/KTGwiu4p8BD7C02Gf0A/zizmkPGwrJ2xDCzJeJVZxdD2iSW7+SSRO1HLNawgrxsPpa52o22WAQHgPCosAEl8IX0WCWlO/nM0/XIVjJ0utAh2573xlwn5JWULKepPMEldVFTzuMcP1Qd+BMXacJXpuLk8hdgKmbpj2Vxlo/6vVQ36opoVRgD4uNS92DPFM26nWQITTaPh0hmXrPHcRGA4UgogUFa2ee69IY5rJ+iFd/p6XBwLwA+1NUZ2Lej1MhObNaABrUG3m3+ah9fCj6jamccOSDWts+T0lev6XnTiw5BfhvPtvZqn6J9xQ5Z3NwEGQ8YRe3oWdmWFzm48Ax2SiM12FGRu4UTc8Pp/ZOfKcoXOXUTB32YYALEJxawint5BACWy5hO1oPM9CHvjCePooZIYLnIKPLOmrrCJ9xHu/ebK6UsUkUSxS4Cee+Ly8NvP1mBvixD1xXszIpCT2sA9fO5UeEWuGvThEp9KM9Lm6VBI6/fOxw7sF8kvPSXSxMnH7WBXx+LC3D5trcUxXKbltoNyZzPF5dYd5DDCoBQtP5EyLDtDZ80mo=,iv:zlQWvgiYgGX5+CFp+xng4h9wxr2H/m73XO4q5CSuao4=,tag:YjVt1YTIleSGMDVsCG0M5A==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T23:52:15Z"
    mac: ENC[AES256_GCM,data:RsxEzHDjHa1KHfchTi3jLL4PxOpHfcT+x9FlnA1P54ZpBQckuFg+Wb626nPY1q8cgQcmqOnxvagXnu790hMUJhNUJNFPpeCFhJoo2ytTkJ/AoXR/PTOTS6rT4xxErcvGiezof2Vi2SVc3+qRfrQZv6ef2UyUdsOx9jVFmqKbWSo=,iv:FnF4Sz0xsZVWHuqdInDyRKHPKMc5DBKeRJgN3FiKFKM=,tag:QRh2tRFFDVfGIWEvxXTakA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
