apiVersion: v1
kind: Secret
metadata:
    name: samba
    namespace: media
stringData:
    samba.yaml: ENC[AES256_GCM,data:/RmS6Rb1eWO1VzrC0xo6JpVSeZZcsZu201EsyIzd1cvy3prU6l0igF+4/uRbvsm9Pz2+h0aZX85zqvqgagZVmzAAvIv4T4Gwvl2l3gsLw6BM3Mt1rOHMH1faeXZGO63vY7F4ucNieijhQ8RkDAbGEsx3BKp64Hsm9Y6BEnrzK4D3S6xjCkoC4m5/f9G9+xXd2HX3ytn5jtW3YFTxy1sFQN8MOA1WStSqbxIdKDV7lu8N0nJjBQsh1SorhrRGh1KYaYTdhO/InOgMafU9LpdmKnczggFKFO/RwUNTMCXOeLevNw2g0ze9NVabj5o5eGB3xcnfE3OkG72FqUx7AD1BC21l68gOQEApB+oc8pITOdMr+g9Whx10OWPEWeZU/UQAeKkHi2tu5ZgnLeFi5h0rkN5s5OTVkFe5YEK6EioaF/RKY44HGLFogjDTHBw07z+4pZyb6wfA5g0h57EXvfpNJ7yjltYy/K9M,iv:+9DWEpMOW/7Pqn0YS2GiZ0674yllTCC5bHOgjOGcl0k=,tag:f8Iftmx9bwEQjkE2fQklDw==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T23:28:12Z"
    mac: ENC[AES256_GCM,data:XCcFfS30rOliF551FhqzTb/1jVxakHl/jAI5wpH0K+08CCj+8GAUP2ZigmjrOu8v0k0rviqvGdeZ2gNtl1tnNKNeK0sBV/Gq8ZLmgKEZAUP5Iizst4Y/3JywZQHnsGUNDKcpVSRvf0ldKBP10IiC/WlgeBECl2BQgY4tdMJxo3M=,iv:GWEpxCfajzjSIh/ori78hrQML1ER0TJDLNIwYIBgy7A=,tag:3lkeNW+LgAs7zojikKihcw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
