apiVersion: v1
kind: Secret
metadata:
    name: samba
    namespace: media
stringData:
    samba.yaml: ENC[AES256_GCM,data:eGODI+HpaCdJ9QOC20fn99yE4O5n1Xq+Z7a5FKx/nRqKhtkSD/ol3uYcrCnAF+bKoet4Ab1kxU/z8GlKlMQb8J3g9mHBmBwZ/iZtF7oO41LyI+/FAyB7SbYFKDnljz1gp4tYctCId8KM+ROOgdL46aeQ9bmrobRIw/MwLaQAiQYG+uVeBScWffngNVbICcKmRbafhJxPKSAdN7AYL0JARuUZpUW+YJRRgQiyr1+MmLrKYG7ECk9GaaSkXxz5RGee0+ZsX2psDDKdRH6fEqrsgJRC5h6OsUapF12OhjBUDT3JQ5V2FRs/hLXHNHpcIDtyexdTG+MWOHrEkG7lmuXJfLTHNsfpA/cKTqPoVd0rXJq8riRQilmAfJYYRJ7R0+HocVGAXbR7kBGp9GL3vQMqnTMPbxrXwvZs2pJDP1kWhxveDKK0SKhuS471WbgyNrfhdrlGbOMR+OKIX1E+SM3seRdVYNhRR3CetGUWkxJky4vqvw6Ysbqy76zEVbpXBP2GV9kAoK/5aqPeVTfIiU95wSKoBg3rK0MYKm/bCvHYlkXm/V5FmT5bmHuThjmCHDbdKSC0DCZf7phtEjTikAeQY1LlCMSG7V2ARdY=,iv:gpahmoyYZefZbSaJA0n5a+NPBR/LATxdem1mQAwDegY=,tag:DKycAslUfi82RhtEWBu26A==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-04T23:33:19Z"
    mac: ENC[AES256_GCM,data:EMIoXzJSo8yNV0BbGDe+dDfT3Qc8cY40JGl2G0SikZ9IglnkK7X3iQHePT7UylxBTt3fugbTnC+gfmG45sKS67nP+UySt59Hg4XzJh8hkjn37MrTKNYvM8/VG4NLMsKiezYj5m2NH61+FHaVARXOQ4yEHK0BB93JFkVY2EYQkwA=,iv:Lgbc0eehrdJjvwD/0EyhBcEb1ZXUaCMKl5yNe5hM8U0=,tag:GQpeyw39+f13f9wuBk7HUg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
