# flux/apps/curl-test-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: curl-test
  namespace: media
spec:
  restartPolicy: Never
  containers:
    - name: alpine-curl
      image: alpine:latest
      command: ["/bin/sh", "-c"]
      args: ["apk add --no-cache curl && curl https://ifconfig.me; sleep 3600"]
