apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:E+0uXiRXDFo42iuY8zcKtbXTh7C3YhTvwyIb2KiPdfiJZ1RzvYT8yA==,iv:NYGAg/mZOFN3xD+8ato/bZbvoO1Q0u596ov6tHUP2Zk=,tag:WHnOJiw+Ud+P3f8EVtYtJw==,type:str]
sops:
  age:
    - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQmt5UUFCN3gzVnlFNXBi
        QXlhMlRIQWFyZnlZZnQ2OC90MnNmcmdEdkJrCitvU0EzUzV4TENHeFRlZzZJUEtP
        RjFIWUxkdUdiZmpON2laZWtGVW8xQjAKLS0tIERZaGg2QmRMYUlSNG9zeGZPa1Nh
        cWFXVnFuVEF0K3kvV3F6d0dCQU1WTjAK0RTpwobaYCGBgZq95OW7N1cuF28i8kGx
        /yUKjujsXZu3tbcJy4+ZgBGghTOh2A/JqbNeC9p4O1We5u9qxzaOOw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T18:45:11Z"
  mac: ENC[AES256_GCM,data:Nv2AmVSXz6nsh1NnDw3/V28FM7ryTk+68zMysBbEwIsDLE+JXolF6wsrtVayGNMxShklD/ArllEw7UtFI5yFoNN1TNjdGPGDsFfckhD50W533PI6FGcVwiU2tbrET8SNZ25Xk1IvFrzSSO5tl8LNj6zZPfPiWCB0DyhPqs+eTGE=,iv:XIgne8AnjE4mX654ZxruKszYG8kPQkOZNrrlzGSKLS8=,tag:qg3AtoF4m15zoMEAG+zrWg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
