---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app linstor-test
  namespace: flux-system
spec:
  targetNamespace: piraeus-test
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: piraeus-operator-test
  path: ./kubernetes/apps/piraeus-test/linstor/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app linstor-storageclass-test
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: linstor-test
  path: ./kubernetes/apps/piraeus-test/linstor/storageclass
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m