apiVersion: v1
kind: Secret
metadata:
    name: akeyless
stringData:
    accessId: ENC[AES256_GCM,data:SwtXjYfhTN0HrdO4hlRzew==,iv:GebJk3RuJp91xWTrlBVXHE6ZKiyETW8gHr73ZRt7hSQ=,tag:7Y5y6+shbOGBXbjm2VmMpQ==,type:str]
    accessType: ENC[AES256_GCM,data:NTOzhn2DzQ==,iv:hdgS2xuBOJI2jYEVyj1LZ7LGMDBoROMsrIPmdDfUxU4=,tag:Gkqhiztq0uU6M9YqY/cCCg==,type:str]
    accessTypeParam: ENC[AES256_GCM,data:i+w6JxiBvheTnBLog52TeDwjnDkw1mLChTx+UA2Q5zfNQyZyLk6fL06P5BA=,iv:2CeQ8GvF/JlUTSaHs4M2JccjAzu99qDZUyN2Q5inv4Y=,tag:Jd6DqpFwWVLRBp9m16G2EA==,type:str]
sops:
    age:
        - recipient: age148pw05egkn080d47jyyexv4358cgug87farl2caa340wxw3s7pjq89sk86
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUlUelkzbUt6MTltb0RB
            bzBVN1liaUV5OFJDeUN0NjZsVnR1Q1dUcmo0CnF4bmdRWFNnaVJMaDl6N2pkYVlT
            QVMyZEF5MkhVdHlRc0JxUXNzeXA5b1UKLS0tIGJCZnVDRko3YW5naVVFcDBjWEJH
            YnJZdHlMUzZkNVBQVTVNSWdnRFZqejQK+p5BqHYYHUNrhbqLWkpl2treSlMZmSrY
            It5ZYad/Nkzsmth4fNdHnsM885DJ8SAJcuT1S0uEMHC17KDHJreUwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-10T14:23:49Z"
    mac: ENC[AES256_GCM,data:huJptWaBatu6Dk4JSQrNBp53yEEXQnRo+GJHj4CzNU9/7Unx2BjBu3eotXc0Z66klM7ivNZf+pA3Cp0YVL5TOVfRY19FX9/eFuREPPoao03xL76q5YolB3rIrV+cWXJ974HB5T7zihVoBJwIPfW2TKtj1CBLBnHSe6DEI8Kgywg=,iv:L7e1rPlwkWkBRsIJuqqlVU4BADceAdxh4a1V2LbAcz0=,tag:NFUU6i9tlFNVKXXWl/vTZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
