---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: network

components:
  - ../../components/sops
  - ../../components/repo

resources:
  - ./namespace.yaml
  - ./cloudflare-dns/ks.yaml
  - ./cloudflare-tunnel/ks.yaml
  - ./pihole-dns/ks.yaml
  - ./envoy-gateway/ks.yaml
  - ./k8s-gateway/ks.yaml
  - ./vpn-gateway/ks.yaml
